#!/usr/bin/env bash
set -euo pipefail

CONFIG="${CONFIG:-examples/regtest.toml}"
BITCOIN_DATADIR="${BITCOIN_DATADIR:-/tmp/bitcoin-regtest}"
SV2_HOST="${SV2_HOST:-}"
SV2_PORT="${SV2_PORT:-}"
TPROXY_PORT="${TPROXY_PORT:-34255}"
TPROXY_CMD="${TPROXY_CMD:-translator-proxy}"
CGMINER_CMD="${CGMINER_CMD:-cgminer}"
CGMINER_USER="${CGMINER_USER:-regtest_cpu}"
CGMINER_PASSWORD="${CGMINER_PASSWORD:-x}"
TPROXY_CONFIG="${TPROXY_CONFIG:-dev/regtest/generated/tproxy.toml}"

require_command() {
  local command_name="$1"
  local setup_hint="$2"

  if ! command -v "${command_name}" >/dev/null 2>&1; then
    echo "missing required command: ${command_name}" >&2
    echo "${setup_hint}" >&2
    exit 127
  fi
}

toml_string() {
  local key="$1"
  local file="$2"

  sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\"\(.*\)\"[[:space:]]*$/\1/p" "${file}" | head -n 1
}

toml_number() {
  local key="$1"
  local file="$2"

  sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\([0-9][0-9]*\).*$/\1/p" "${file}" | head -n 1
}

parse_host() {
  local listen_address="$1"
  local host="${listen_address%:*}"

  host="${host#[}"
  host="${host%]}"
  if [[ -z "${host}" || "${host}" == "0.0.0.0" || "${host}" == "::" ]]; then
    host="127.0.0.1"
  fi
  printf '%s\n' "${host}"
}

parse_port() {
  local listen_address="$1"

  printf '%s\n' "${listen_address##*:}"
}

require_command bitcoin-cli "Install Bitcoin Core and make sure bitcoin-cli is on PATH."
require_command "${TPROXY_CMD}" "Install SRI translator proxy, or set TPROXY_CMD=/path/to/translator-proxy."
require_command "${CGMINER_CMD}" "Install cgminer, or set CGMINER_CMD=/path/to/cgminer."

if [[ ! -f "${CONFIG}" ]]; then
  echo "config not found: ${CONFIG}" >&2
  exit 1
fi

DATA_DIR="$(toml_string data_dir "${CONFIG}")"
if [[ -z "${DATA_DIR}" ]]; then
  DATA_DIR="./data"
fi
AUTHORITY_KEYS_PATH="${AUTHORITY_KEYS_PATH:-${DATA_DIR}/authority-keys.toml}"
if [[ ! -f "${AUTHORITY_KEYS_PATH}" ]]; then
  echo "authority keys not found: ${AUTHORITY_KEYS_PATH}" >&2
  echo "Run: cargo run -- check --config ${CONFIG}" >&2
  exit 1
fi

AUTHORITY_PUBLIC_KEY="$(toml_string authority_public_key "${AUTHORITY_KEYS_PATH}")"
if [[ -z "${AUTHORITY_PUBLIC_KEY}" ]]; then
  echo "authority_public_key missing from ${AUTHORITY_KEYS_PATH}" >&2
  exit 1
fi

LISTEN_ADDRESS="$(toml_string listen_address "${CONFIG}")"
if [[ -z "${SV2_HOST}" ]]; then
  SV2_HOST="$(parse_host "${LISTEN_ADDRESS:-0.0.0.0:3333}")"
fi
if [[ -z "${SV2_PORT}" ]]; then
  SV2_PORT="$(parse_port "${LISTEN_ADDRESS:-0.0.0.0:3333}")"
fi

SHARES_PER_MINUTE="$(toml_number shares_per_minute "${CONFIG}")"
if [[ -z "${SHARES_PER_MINUTE}" ]]; then
  SHARES_PER_MINUTE="6"
fi

mkdir -p "$(dirname "${TPROXY_CONFIG}")"
cat >"${TPROXY_CONFIG}" <<EOF
# Generated by dev/regtest/scripts/cgminer-through-tproxy.sh.

downstream_address = "0.0.0.0"
downstream_port = ${TPROXY_PORT}

max_supported_version = 2
min_supported_version = 2
downstream_extranonce2_size = 4

user_identity = "${CGMINER_USER}"
aggregate_channels = true

supported_extensions = [
    0x0002,
]

monitoring_address = "0.0.0.0:9092"
monitoring_cache_refresh_secs = 15

[downstream_difficulty_config]
min_individual_miner_hashrate = 10000000.0
shares_per_minute = ${SHARES_PER_MINUTE}
enable_vardiff = true

job_keepalive_interval_secs = 60

[[upstreams]]
address = "${SV2_HOST}"
port = ${SV2_PORT}
authority_pubkey = "${AUTHORITY_PUBLIC_KEY}"
EOF

BEFORE="$(bitcoin-cli -regtest -datadir="${BITCOIN_DATADIR}" getblockcount)"
echo "generated_tproxy_config=${TPROXY_CONFIG}"
echo "sv2_upstream=${SV2_HOST}:${SV2_PORT}"
echo "sv1_downstream=127.0.0.1:${TPROXY_PORT}"
echo "before=${BEFORE}"

"${TPROXY_CMD}" -c "${TPROXY_CONFIG}" &
TPROXY_PID="$!"

cleanup() {
  kill "${TPROXY_PID}" >/dev/null 2>&1 || true
  wait "${TPROXY_PID}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

sleep 2

"${CGMINER_CMD}" \
  -o "stratum+tcp://127.0.0.1:${TPROXY_PORT}" \
  -u "${CGMINER_USER}" \
  -p "${CGMINER_PASSWORD}"

AFTER="$(bitcoin-cli -regtest -datadir="${BITCOIN_DATADIR}" getblockcount)"
echo "after=${AFTER}"
